### ISSUE TITLE
Should show reasons why users downvote a reply

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#120]
In API, `ArticleReplyFeedback` object type has `comment` field containing the reason why a LINE user downvotes a reply. These reasons should be shown in the website so that editors can improve the reply.

In the reply feedback count display, we should display the list of  `comment` (reasons) why the users think the article-reply is useless.

For minimal UI, we can put a link beside the downvote count and leverage the current `<Modal>` to display the downvote reasons:

<img width="211" alt="2019-03-06 10 26 33" src="https://user-images.githubusercontent.com/108608/53888252-f7341580-405e-11e9-9add-b963f6f86ad4.png">

<img width="253" alt="2019-03-06 10 24 25" src="https://user-images.githubusercontent.com/108608/53888122-acb29900-405e-11e9-92e3-5c9ca51d147c.png">

**Comment by MrOrz** [comment]
Oops, it's a duplicate of #97 . Cloising this.

**Comment by MrOrz** [comment]
Reopen because #97 is now scoped down to submission of reason only.

**Comment by leannechen** [comment]
請問我可以認領這個嗎～
