### ISSUE TITLE
Spammy structured markup

### ISSUE THREAD

**Issue by GoreStarry** [cofacts/rumors-site#128]
https://github.com/cofacts/rumors-site/blob/8affd302fbaf275e3db272e39635c64278894ead/pages/_document.js#L10

雖然搞不清楚之前為何會被 reject，但如果是 schema.org 引起的，反正現行 schema.org 也沒有實質反應內容，與放著反被扣分，要不先拿掉重審看看？

![image](https://user-images.githubusercontent.com/13726538/44139988-5b99c6c2-a0ab-11e8-8f3f-581a27152178.png)

---

目前我的搜尋「cofacts」在二頁3位（發現目前沒首頁 head 沒 title，所以抓的是 h2 ）

![image](https://user-images.githubusercontent.com/13726538/44140800-c8fa38c6-a0ad-11e8-9453-743b56748fbb.png)

**Comment by MrOrz** [comment]
同意嗚嗚嗚
請拔請拔

然後應該要補個 title Orz

**Comment by MrOrz** [comment]
Follow-up:

Review is requested.

![2018-08-25 12 14 07](https://user-images.githubusercontent.com/108608/44614863-caa57280-a85f-11e8-91fd-a4010d88c976.png)
