### ISSUE TITLE
Landing page not displaying normally on phones

### ISSUE THREAD

**Issue by changhc** [cofacts/rumors-site#135]
The landing page's CSS for mobile devices needs revision.
And maybe a separate style for i18n? See the second screenshot, which was captured with my phone.

![screenshot from 2018-08-26 07-25-28](https://user-images.githubusercontent.com/4591982/44623456-8a96cc00-a901-11e8-9075-0b19b706456a.png)

![screenshot_2018-08-26-07-14-18](https://user-images.githubusercontent.com/4591982/44623445-1825ec00-a901-11e8-81f1-7c273a494a07.png)

**Comment by MrOrz** [comment]
This issue should belong to landing page repo: https://github.com/cofacts/grants-landing-template
