### ISSUE TITLE
Different user's level popup is overlapping together

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#152]
Despite the fact that cofacts/rumors-api#95 is fixed by @nonumpa 's cofacts/rumors-api#123, the user level display is still incorrect.

![overlapping](https://user-images.githubusercontent.com/108608/52536804-3e99ef80-2d9a-11e9-8575-5f50e49342a3.gif)

Seems that all user's level popups are all overlapping together.

Example: https://cofacts.g0v.tw/article/3qlrkscnnx950

It's a good first issue I think.

**Comment by nonumpa** [comment]
According to the [meeting note](https://g0v.hackmd.io/1wmM-FIiTVSbw0BldFoZTg) : use balloon.css instead.

I use `npm install balloon-css`, but don't know how to import it correctly.

`import 'balloon-css'` is not work, but `import '../node_modules/balloon-css/balloon.css'` seems not good.

Here is the [commit](https://github.com/cofacts/rumors-site/commit/f905d7c1d83f804431b63a9319a77d68b622e65a).

**Comment by MrOrz** [comment]
#153 fixes this.
