### ISSUE TITLE
Use navigator.share to share replies

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#180]
In #62 we implemented the copy function. But in mobile environment, most browsers has a native `navigator.share` that will trigger share dialog:

https://pjchender.blogspot.com/2019/11/webapis-web-share-api-navigatorshare.html

I think we can use `navigator.share` when the function exists; the current mechanism (copy to clipboard) can act as a fallback when the browser don't support `navigator.share`.

**Comment by kevin10410** [comment]
Ongoing

**Comment by MrOrz** [comment]
Implemented in #192 . Thank you @kevin10410 !
