### ISSUE TITLE
AbortError: Share canceled

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#205]
View details in Rollbar: [https://rollbar.com/mrorz/rumors-site/items/19/](https://rollbar.com/mrorz/rumors-site/items/19/)

![image](https://user-images.githubusercontent.com/108608/73838238-327e2c00-484e-11ea-94ce-72537aec3910.png)

```

AbortError: Share canceled

```

Also: https://rollbar.com/mrorz/rumors-site/items/60/

Seems that canceling mobile share will throw errors. We should catch these errors and do nothing.

**Comment by normanlinnet** [comment]
https://github.com/cofacts/rumors-site/pull/216
