### ISSUE TITLE
Entering article page from article list takes 2 back to go back to list page

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#211]
![image](https://user-images.githubusercontent.com/108608/73603451-bf5e8680-45bd-11ea-8700-e4d9765dad22.png)

## Steps to reproduce

1. Enter list page https://cofacts.g0v.tw/articles?filter=solved
2. Click any of article to enter article page
3. Wait for the search trend iframe to load 
4. Press back on browser

## Expected

The browser stops loading and go back to article list

## Actual

The browser stays at article page. When search trend is loaded, it displays a huge number (indicating that article id is gone, but list page not loaded instead)

**Comment by normanlinnet** [comment]
A similar problem: 看起來類似的問題
https://github.com/ReactTraining/react-router/issues/6259

**Comment by MrOrz** [comment]
Cool. Not sure if router used by next.js share similar root cause.

**Comment by jihchi** [comment]
I've observed that we won't get the issue if you comment out the `<Trendline />` component which is aligned with [iframe issue](https://github.com/cofacts/rumors-site/issues/211#issuecomment-586492770) that @normanlinnet mentioned.

I'll continue to dig into the problem and see if I can find a way to solve it.

**Comment by MrOrz** [comment]
Thank you @jihchi for locating the component that caused this issue!

We recently have [plans](https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=681%3A0) to replace the iframe with line charts (data from Google Analytics reporting API). Let's hope the problem can go away soon.

**Comment by MrOrz** [comment]
Confirmed that it's fixed via #314.
