### ISSUE TITLE
Fold hyperlink previews in detail pages

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#274]
Implement hyperlink folding when there are more than 4 hyperlinks. [Visual spec](https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=2079%3A939)

![image](https://user-images.githubusercontent.com/108608/87218122-81426b80-c382-11ea-9f4b-d8852d09f385.png)

- 1~3 hyperlinks: show all
- 4+ hyperlinks: fold to 2 hyperlinks and a "show" button
- No "collapse" button after expansion

**Comment by jiru** [comment]
Working on this.
