### ISSUE TITLE
Fix logout in mobile menu

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#284]
Clicking this button has no effect:
<img width="566" alt="截圖 2020-07-11 下午8 53 04" src="https://user-images.githubusercontent.com/108608/87224542-a18d1d00-c3b8-11ea-86dd-fb40784e3aba.png">

It should work the same as its desktop counterpart.

**Comment by jojomango** [comment]
I think this issue already be fixed

**Comment by MrOrz** [comment]
Confirmed on production. Seems that it's fixed in #352. Thanks for keeping our backlog clean!
