### ISSUE TITLE
Don't insert friend link to clipboard for logged-in users

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#350]
From [1007 testing feedback](https://g0v.hackmd.io/CCecwMdhT_eTPQmNfzQTzQ#%E6%9C%AA%E7%AB%9F%E9%A0%85%E7%9B%AE)

In #340  we insert add-friend link at the end of clipboard when user copies text from reply.

However, for logged-in editors, it will interfere the fact-checking process, thus should be removed.

We can safely assume that logged-in users are not the target of the add-friend link.

**Comment by eob** [comment]
I can take a crack at this! 🤖
