### ISSUE TITLE
Provide better placeholder for editors

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#361]
Discussion see [20201209 meeting note](https://g0v.hackmd.io/@mrorz/cofacts-meeting-notes/%2FNqPf1SfPQEGOZ3Z6h7Q7wA)

## As-is

Currently the editor UI shows `140 字以內` no matter what reply type the editor has chosen. When shown this UI, editors are not instructed to input useful reply here.

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/108608/102174085-8d08ff80-3ed7-11eb-8232-27479d756b90.png">

## To-be

Replace `140 字以內` placeholder with the following:

### When `replyType === 'NOT_ARTICLE'`:

Please briefly explain why this message should not be processed in Cofacts
請簡單說明為何 Cofacts 不該處理這則訊息

### When `replyType === 'NOT_RUMOR'`:

As a brief intro for the references, please point out which part of the message is correct.
請簡單說明它哪個部分是正確的，作為「資料來源」的導讀

### When `replyType === 'OPINIONATED'`:

Please briefly:
1. explain which part of the message contains personal opinion
2. remind the audience that this is not factual

請簡單說明：
1. 它哪個部分含有主觀意見之處
2. 提醒讀者這不是客觀事實

(Note: textarea placeholders [can include line breaks](https://stackoverflow.com/questions/7312623/insert-line-break-inside-placeholder-attribute-of-a-textarea). )

### When `replyType === 'RUMOR'`:

As a brief intro for the references, please point out which part of the message is incorrect.
請簡單說明不實之處，作為「資料來源」的導讀

**Comment by ulayab** [comment]
(舉手)

**Comment by MrOrz** [comment]
Fixed in #383, kudos to @ulayab !
