### ISSUE TITLE
Fix editor RWD breakpoints

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#363]
From [20201209 meeting note](https://g0v.hackmd.io/NqPf1SfPQEGOZ3Z6h7Q7wA#mobile--desktop):

Breakpoint 設定有誤，mobile 與 desktop 版中間有一個出處沒有標題的版本：

![](https://s3-ap-northeast-1.amazonaws.com/g0v-hackmd-images/uploads/upload_7a650fa0654e0df850badd851fb0c489.png)

In this case please all go for desktop style.

**Comment by Young-TW** [comment]
@MrOrz can close this issue?

**Comment by MrOrz** [comment]
> @MrOrz can close this issue?
👌 👌 👌 
<img width="368" alt="圖片" src="https://user-images.githubusercontent.com/108608/145667829-926bf7a6-8ae1-4061-b904-537d5e9baba3.png">
