### ISSUE TITLE
Content too long and cause horizontal scroll on mobile

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#390]
Discovered at [20210120](https://g0v.hackmd.io/@mrorz/cofacts-meeting-notes/%2FJUVhhxSmSx62O5SUVuJ1rw) release check.

Ex: 
https://dev.cofacts.org/article/37rwpsmfuqeiz
![image](https://user-images.githubusercontent.com/108608/108160020-344a2300-7123-11eb-9d5f-3f9fcfa22e89.png)

**Comment by playpool513** [comment]
I'd like to pick this up. Will try to finish this today.

**Comment by MrOrz** [comment]
Seems fixed, kudos to @playpool513 !
