### ISSUE TITLE
Facebook timeline-like time display

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#396]
discussion: https://g0v.hackmd.io/CqKV8gfNSfyuvdQOtq7TlQ#%E6%99%82%E9%96%93%E9%A1%AF%E7%A4%BA

## as-is
All time display is relative to current time.
It was set like this because in server-side rendering, the time zone is GMT, this relative time was chosen by default.

## to-be
Use facebook-like time display as discussed in https://g0v.hackmd.io/CqKV8gfNSfyuvdQOtq7TlQ#%E6%99%82%E9%96%93%E9%A1%AF%E7%A4%BA .

For time zone issue, we can
- keep ISO Timestamp in `<time>` HTML property so that search engine can read the time correctly
- apply absolute time display on component mount, which should only trigger on browsers

Note: We can use [`Intl.DateTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat) or [`Intl.RelativeTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat) if we find that date-fns v2's translation is not good enough. Browser translation seems to be more stable, since date-fns locale rule is [difficult to understand](https://github.com/date-fns/date-fns/blob/master/src/locale/zh-TW/snapshot.md).

**Comment by kerrickstaley** [comment]
我會今天看這個項目。
