### ISSUE TITLE
Reorder categories so that marked and categories from similar articles can appear in the front

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#397]
## As-is
The category dialog sorts the category using arbitrary order (same order the API has returned)
![image](https://user-images.githubusercontent.com/108608/108950382-1dff1280-76a1-11eb-9be4-9e491846c290.png)

## To-be

Per discussed in [20210217](https://g0v.hackmd.io/CqKV8gfNSfyuvdQOtq7TlQ#推薦標籤), we should
- Move categories that has been added to the front
- Then list out categories that is also marked in similar articles
- Then the rest of the categories.

**Comment by kelvin2go** [comment]
```
Move categories that has been added to the front
Then list out categories that is also marked in similar articles
Then the rest of the categories.
```

how to find the `Then list out categories that is also marked in similar articles` ?
@MrOrz

**Comment by MrOrz** [comment]
Hi @kelvin2go ,

Thanks for taking a look! It can be retrieved by modifying the [current GraphQL query](https://github.com/cofacts/rumors-site/blob/master/pages/article/%5Bid%5D.js#L131) to include categories.

```graphql
query LoadArticlePage($id: String!) {
  GetArticle(id: $id) {
    # ... Other fields ...
    similarArticles: relatedArticles {
      edges {
        node {
          # ... Other fields for the similar article ...
          articleCategories {
            categoryId
          }
        }
      }
    }
    # ... Other fields ...
  }
}
```

![image](https://user-images.githubusercontent.com/108608/135952661-4a730cf3-f499-4c50-bb6c-3fb4f953cab9.png)
