### ISSUE TITLE
Openpeeps avatar is not shown in landing page

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#417]
## As-is
![image](https://user-images.githubusercontent.com/108608/111423121-c5b0b300-872a-11eb-9650-7409f96834aa.png)

## To-be
Openpeeps avatar should show in the same way as in other pages 
![image](https://user-images.githubusercontent.com/108608/111423263-fbee3280-872a-11eb-9bac-27be22aa784e.png)

**Comment by ulayab** [comment]
Hi @MrOrz
I just fixed this issue, and wondering which branch should I PR to ? thx🙏

**Comment by MrOrz** [comment]
Hi @ulayab ,
Please open a PR to `master` branch. Thanks!
