### ISSUE TITLE
Show author of reply requests (article comments)

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#425]
We should show author of reply requests, as depicted in [figma](https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=681%3A0).

## Mobile
![image](https://user-images.githubusercontent.com/108608/113914992-c4961180-9810-11eb-89cf-31b78f363609.png)

## Desktop
![image](https://user-images.githubusercontent.com/108608/113914962-bba54000-9810-11eb-9568-4c47bab8117d.png)

**Comment by fufuShih** [comment]
I would like to try to complete this pull request.

**Comment by mojoee** [comment]
has this issue been completed?

**Comment by fufuShih** [comment]
@mojoee ,
Since there has been no response, the issue has not yet begun.

**Comment by mojoee** [comment]
I'm not clear which part in the figma we are referring to. Where should the author of the reply requests been shown?

**Comment by MrOrz** [comment]
Sorry for the confusion. Here are the figma links to the section:

Mobile: https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?type=design&node-id=1236-1275&mode=design&t=1pfTEpeMi9zgygTz-4
Desktop: https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?type=design&node-id=890-294&mode=design&t=1pfTEpeMi9zgygTz-4
