### ISSUE TITLE
Incorrect "Similar replies" title

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#434]
In reply page, the sidebar title should be "Similar replies" rather than "Similar messages".
![image](https://user-images.githubusercontent.com/108608/117537599-96386b80-b034-11eb-8cdc-f3f0de947d41.png)

**Comment by luoyu54321** [comment]
[from g0v hackathon] 我先認領這一題（by Kiki）

**Comment by MrOrz** [comment]
感謝 @luoyu54321 !
Setup 有問題的話可以隨時在 Gather 發問唷～

**Comment by MrOrz** [comment]
Fixed in #437, kudos to @luoyu54321 !
