### ISSUE TITLE
Do not allow empty replies

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#449]
Currently there are empty replies like this in the DB:
https://cofacts.tw/reply/UkJBtHoBgBgcuemX5aeB

We should block empty replies when submitting on website & also block it on API side.

Also, replies with only space / blank lines should be blocked too. Consider `trim()` before checking its emptiness.

Relates to cofacts/rumors-line-bot#285

**Comment by jwjeng** [comment]
若只擋空字串或空白字元，有心人只要隨便打幾個字就可以騙過，所以怎樣的狀況應該視為是來亂的而忽略掉，可能要再討論一下吧?

**Comment by MrOrz** [comment]
如果有違反使用者條款的狀況，我們可以直接尋條款刪除唷

目前實際有刪掉的狀況可以看 https://github.com/cofacts/takedowns ～
