### ISSUE TITLE
Add introduction youtube video to Tutorial page

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#462]
From: https://g0v.hackmd.io/@mrorz/cofacts-meeting-notes/%2F-G9Md9IyQauRoalIXJgenQ

Put this
https://www.youtube.com/watch?v=WfdfB7GyqMY

in this
https://cofacts.tw/about

![圖片](https://user-images.githubusercontent.com/108608/145665971-0615598b-2c9b-4a47-9ec9-f367580a1a33.png)

Width: align with container
Height: make it proportional (Around 16:9) across all sizes

**Comment by Pongy-jr** [comment]
Hi could you assign this to me, I would like to work on this.
