### ISSUE TITLE
Add links to website footer

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#520]
From https://g0v.hackmd.io/VVIOZobARkegK3vxYdG52Q?view#%E7%B6%B2%E7%AB%99%E8%A8%B1%E9%A1%98

Add the following links to website footer
<img width="1324" alt="圖片" src="https://user-images.githubusercontent.com/108608/207518672-d9cf7031-e0fe-4635-b891-5e17d8ec3149.png">

| Text (En) | Text (Zh) | To column | Link |
| -- | -- | -- | -- |
| Donate to Cofacts | 捐款給 Cofacts | Contact | https://ocf.neticrm.tw/civicrm/contribute/transact?id=48 |
| Impact Report | 影響力報告 | About | `/impact` |

Duplicates #430

**Comment by marcussfu** [comment]
我想改這個
