### ISSUE TITLE
Use hashed asset path

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#57]
Example: https://github.com/zeit/next.js/tree/canary/examples/with-hashed-statics

This can be used for `<img>`  tags as well as *.style.css files, which contains styled-jsx CSS.

**Comment by LucienLee** [comment]
Close by #63

**Comment by MrOrz** [comment]
結果 next-js v5 支援 universal webpack
應該可以用 url-loader 解掉⋯⋯ XD
