### ISSUE TITLE
Add a "share" or "copy to clipboard" button in each reply

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#62]
## Use cases

1. Users found the desired reply on cofacts.g0v.tw and want to share to LINE or other places.
2. Editors found a reply to copy from when replying other articles.

Currently, the user will have to copy "含有真實訊息" / "含有不實訊息", the reasons and the references separately. When the URL in the references are too long, the URLs gets truncated, and will become unusable after paste.

## Proposed solution

Add a "Share" or "Copy to clipboard" button to each replies. (Article page)
<img width="789" alt="2019-03-06 10 31 50" src="https://user-images.githubusercontent.com/108608/53888527-b5f03580-405f-11e9-8094-fe17d0a55e99.png">

For example, in an article page like this:
https://cofacts.g0v.tw/article/AV_pZ0PPyCdS-nWhujrf

When the 'share' or 'copy to clipboard' button is pressed, the following text should be shared or put in to the clipboard:

```
⭕ 含有正確訊息

理由：
尋人持續進行中。

出處：
https://www.facebook.com/permalink.php?story_fbid=1677448952276114&id=100000330760687
尋人
https://www.youtube.com/watch?v=yad0JzYfzuY&feature=youtu.be
女大生離家失蹤4天

---
看看其他回應：https://cofacts.g0v.tw/article/AV_pZ0PPyCdS-nWhujrf
```

## Tech reference

Native "share" on Google Chrome mobile:
https://developers.google.com/web/updates/2016/09/navigator-share

Cross-browser clipboard solution
https://clipboardjs.com/

**Comment by ooookai** [comment]
**Template**
```
此訊息已於 [Cofacts 真的假的] 查證為「Ｏ含有正確訊息」 
理由：
ＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸ
ＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸ
ＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸ
ＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸ

出處：
https://cofacts.g0v.tw/article/AV_pZ0PPyCdS-nWhujrf
```

**Comment by MrOrz** [comment]
編輯社團有人提出一樣的建議囉 :D
https://www.facebook.com/groups/cofacts/permalink/2055948657970286/

Use case 是，（具有 google 能力的）編輯透過 google 進入網站，然後希望能從網站輕鬆複製東西進 LINE。編輯不用 LINE bot 的理由是，他收到的訊息是圖片，但目前網站不支援圖片這樣。

編輯建議的樣板跟 @ooookai 的 template 有一模一樣的結構，看來這個 template 很符合直覺。不過，我很喜歡 FB 裡建議的標點符號與 emoji 的用法，我覺得可以參(ㄔㄠ)考(ㄒㄧˊ) XD

**Comment by MrOrz** [comment]
@ooookai 我發現蘭姆酒土司的文章頁面有用 Line share plugin，按一下就直接到 Line 轉傳頁面了，比 html share plugin 少一步

https://media.line.me/zh_TW/

**Comment by leannechen** [comment]
正在製作中～

**Comment by MrOrz** [comment]
@leannechen 's fix is looking good on Cofacts now. Thank you!
Now can close this :)
