### ISSUE TITLE
Ask why a user think an article-reply is useless

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#97]
If an user clicks "X", display a [`prompt`](https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt) for the user to input reason.

API: https://github.com/cofacts/rumors-api/issues/75

<img width="714" alt="2019-03-06 10 05 17" src="https://user-images.githubusercontent.com/108608/53887025-56dcf180-405c-11e9-8819-e9a4f55721dc.png">

**Comment by MrOrz** [comment]
In API, `ArticleReplyFeedback` object type has `comment` field containing the reason why a LINE user downvotes a reply.

**Comment by jihchi** [comment]
Should we prepare few of pre-defined answers such that user could select one of those pre-defined answer or leave an open-text if the user does not found any suitable answer?

**Comment by MrOrz** [comment]
I suggest open text. For simplicity, Let's just use `window.prompt` before our designer @LucienLee come up with better design lol

**Comment by MrOrz** [comment]
Pushed to production. Thanks again @jihchi !
